env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - xo
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
