env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb
  - eslint:recommended
exclude:
  - node_modules
  - vite.config.js
overrides:
  - extends:
    - airbnb-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - vue
rules:
  'indent': 'off'
  '@typescript-eslint/indent': 'off'
